---
# On target machine run: https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
# On ansible machine run: pip install pywinrm
- name: deploy pki
  hosts: pki
  become: true
  gather_facts: yes
  package:
    name: "default-jdk-headless"
    state: present

